CIWEMB-227: Skip collecting payments for completed contributions
compucorp/io.compuco.automateddirectdebit pull request #10
Opened 2023-07-27 10:06 UTC by ahed-compucorp

## Overview
While working on https://github.com/compucorp/io.compuco.gocardless/pull/85, I found two issues: 
- The job fetches the completed contributions
- Using the Mandate Id (created by a payment processor like GoCardless) makes more sense instead of the database's auto-increment ID.

2023-07-27 13:47 UTC, erawat commented
@omarabuhussein  Can you have a look?

2023-07-27 14:03 UTC, omarabuhussein requested changes
@ahed-compucorp few things:

1- We don't care about the contribution "status", we process contributions with total payments < total contribution amount (and it is true that usually "Completed" contribution have total amounts of payments made against it = the contribution total amount, but in certain cases it might not be the case).  

2- 
This is a configurable setting that can be set by the admin through the UI, so it should never be hardcoded here inside this job.
`\Civi::settings()->set('automateddirectdebit_paymentplan_payment_collection_retry_count', 3);`

3- `Using the Mandate Id (created by a payment processor like GoCardless) makes more sense instead of the database's auto-increment ID.`

you are correct on this, my intention was to use the mandate_id actually but seems I made a mistake.

So can you remove everything except 3 ?

2023-07-27 21:55 UTC, ahed-compucorp commented
Thanks @omarabuhussein,

I've updated the PR to keep the mandate change.

2023-07-28 08:18 UTC, omarabuhussein approved these changes
thanks @ahed-compucorp , approved

2023-07-28 10:10 UTC, omarabuhussein requested changes
actually @ahed-compucorp , the ticket number seems to be wrong, can you fix it

2023-07-28 10:11 UTC, omarabuhussein approved these changes

2023-07-28 13:06 UTC, merged